path_categories = "https://storage.googleapis.com/superlinked-recipes/hotels-search/categories.json"
path_dataset = "https://storage.googleapis.com/superlinked-recipes/hotels-search/dataset.jsonl"

log_level = "INFO"

[server]
api_host = "localhost"
api_port = 8080