path_categories = "https://storage.googleapis.com/superlinked-recipes-data/hotels-search/categories/categories.json"
path_dataset = "https://storage.googleapis.com/superlinked-recipes-data/hotels-search/dataset/dataset.jsonl"

log_level = "INFO"

[server]
api_host = "localhost"
api_port = 8080
